### ISSUE TITLE
feature request: link to GitHub repo/contacts on https://john-doe.neocities.org/

### ISSUE THREAD

**Issue by jankovicsandras** [cadars/john-doe#6]
Hi,

Thanks for the great website https://john-doe.neocities.org/ , I think it's fantastic!

Feature request: please add a link to this GitHub repo on the demo website itself. I had a hard time finding this from https://john-doe.neocities.org/ .

Keep up the good work!

**Comment by cadars** [comment]
Thanks for the kind comments! I thought about featuring the repo more visibly than in a footnote, but realized that the website homepage was self-sufficient? (A quick how-to and the two files to download)
