### ISSUE TITLE
Licensing confusion?

### ISSUE THREAD

**Issue by sahansk2** [cadars/john-doe#8]
First, I want to say that this is a very cool project!

I'd like to try to use this template as a starting point for some of my own projects, but I'm not sure how the licensing on the John Doe project works, so I'm hesitant to use or modify it.

Here, this project seems to be AGPLv3 licensed. However, the [Jekyll template](https://github.com/bradleytaunt/john-doe-jekyll) is MIT licensed. These are two extremely different licenses with extremely different implications for distribution.

If I'm to create a derivative work using this project, it would be AGPLv3 for sure and I would have to (among other things) make the code available for all that visit the webpage. But, if I create a derivative Jekyll theme using the other project, I could license that as MIT, and perhaps sublicense it. Is this correct? if not, what is the intended licensing for this project?

**Comment by cadars** [comment]
Just changed the license to public domain, I guess that's better.
